name: CI

on:
  push:
    branches: [ main, mohammed ]
  pull_request:
    branches: [ main, mohammed ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: env
      url: https://github.com

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV


    - name: Debug environment variables
      run: |
        echo "MONGO_URL=$MONGO_URL"
        echo "POSTGRES_USER=$POSTGRES_USER"
        echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
        echo "POSTGRES_HOST=$POSTGRES_HOST"
        echo "POSTGRES_PORT=$POSTGRES_PORT"
        echo "POSTGRES_DB=$POSTGRES_DB"

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
